[[player]]
x = -10.8446
y = 0.01
percent = 0.0
lr = 1.0
situation_kind = 0
state = 'NoAction'
fighter_kind = 93

[player.charge]
int_x = 0

[[player]]
x = 0.0
y = 0.0
percent = 0.0
lr = 1.0
situation_kind = 0
state = 'NoAction'
fighter_kind = -1

[player.charge]

[player.steve_state]
mat_g1 = 36
mat_wood = 18
mat_stone = 0
mat_iron = 3
mat_gold = 0
mat_redstone = 2
mat_diamond = 0
sword_mat = "\u0001"
sword_durability = 25.0
axe_mat = "\u0001"
axe_durability = 70.0
pick_mat = "\u0001"
pick_durability = 70.0
shovel_mat = "\u0001"
shovel_durability = 70.0

[[player]]
x = 0.0
y = 0.0
percent = 0.0
lr = 1.0
situation_kind = 0
state = 'NoAction'
fighter_kind = -1

[player.charge]

[player.steve_state]
mat_g1 = 36
mat_wood = 18
mat_stone = 0
mat_iron = 3
mat_gold = 0
mat_redstone = 2
mat_diamond = 0
sword_mat = "\u0001"
sword_durability = 25.0
axe_mat = "\u0001"
axe_durability = 70.0
pick_mat = "\u0001"
pick_durability = 70.0
shovel_mat = "\u0001"
shovel_durability = 70.0

[[player]]
x = 0.0
y = 0.0
percent = 0.0
lr = 1.0
situation_kind = 0
state = 'NoAction'
fighter_kind = -1

[player.charge]

[player.steve_state]
mat_g1 = 36
mat_wood = 18
mat_stone = 0
mat_iron = 3
mat_gold = 0
mat_redstone = 2
mat_diamond = 0
sword_mat = "\u0001"
sword_durability = 25.0
axe_mat = "\u0001"
axe_durability = 70.0
pick_mat = "\u0001"
pick_durability = 70.0
shovel_mat = "\u0001"
shovel_durability = 70.0

[[player]]
x = 0.0
y = 0.0
percent = 0.0
lr = 1.0
situation_kind = 0
state = 'NoAction'
fighter_kind = -1

[player.charge]

[player.steve_state]
mat_g1 = 36
mat_wood = 18
mat_stone = 0
mat_iron = 3
mat_gold = 0
mat_redstone = 2
mat_diamond = 0
sword_mat = "\u0001"
sword_durability = 25.0
axe_mat = "\u0001"
axe_durability = 70.0
pick_mat = "\u0001"
pick_durability = 70.0
shovel_mat = "\u0001"
shovel_durability = 70.0

[[cpu]]
x = -1.0170566
y = 0.01
percent = 63.0
lr = -1.0
situation_kind = 0
state = 'NoAction'
fighter_kind = 88

[cpu.charge]

[cpu.steve_state]
mat_g1 = 36
mat_wood = 0
mat_stone = 0
mat_iron = 3
mat_gold = 0
mat_redstone = 2
mat_diamond = 0
sword_mat = "\u0001"
sword_durability = 25.0
axe_mat = "\u0001"
axe_durability = 70.0
pick_mat = "\u0001"
pick_durability = 70.0
shovel_mat = "\u0001"
shovel_durability = 70.0

[[cpu]]
x = 0.0
y = 0.0
percent = 0.0
lr = 1.0
situation_kind = 0
state = 'NoAction'
fighter_kind = -1

[cpu.charge]

[cpu.steve_state]
mat_g1 = 36
mat_wood = 18
mat_stone = 0
mat_iron = 3
mat_gold = 0
mat_redstone = 2
mat_diamond = 0
sword_mat = "\u0001"
sword_durability = 25.0
axe_mat = "\u0001"
axe_durability = 70.0
pick_mat = "\u0001"
pick_durability = 70.0
shovel_mat = "\u0001"
shovel_durability = 70.0

[[cpu]]
x = 0.0
y = 0.0
percent = 0.0
lr = 1.0
situation_kind = 0
state = 'NoAction'
fighter_kind = -1

[cpu.charge]

[cpu.steve_state]
mat_g1 = 36
mat_wood = 18
mat_stone = 0
mat_iron = 3
mat_gold = 0
mat_redstone = 2
mat_diamond = 0
sword_mat = "\u0001"
sword_durability = 25.0
axe_mat = "\u0001"
axe_durability = 70.0
pick_mat = "\u0001"
pick_durability = 70.0
shovel_mat = "\u0001"
shovel_durability = 70.0

[[cpu]]
x = 0.0
y = 0.0
percent = 0.0
lr = 1.0
situation_kind = 0
state = 'NoAction'
fighter_kind = -1

[cpu.charge]

[cpu.steve_state]
mat_g1 = 36
mat_wood = 18
mat_stone = 0
mat_iron = 3
mat_gold = 0
mat_redstone = 2
mat_diamond = 0
sword_mat = "\u0001"
sword_durability = 25.0
axe_mat = "\u0001"
axe_durability = 70.0
pick_mat = "\u0001"
pick_durability = 70.0
shovel_mat = "\u0001"
shovel_durability = 70.0

[[cpu]]
x = 0.0
y = 0.0
percent = 0.0
lr = 1.0
situation_kind = 0
state = 'NoAction'
fighter_kind = -1

[cpu.charge]

[cpu.steve_state]
mat_g1 = 36
mat_wood = 18
mat_stone = 0
mat_iron = 3
mat_gold = 0
mat_redstone = 2
mat_diamond = 0
sword_mat = "\u0001"
sword_durability = 25.0
axe_mat = "\u0001"
axe_durability = 70.0
pick_mat = "\u0001"
pick_durability = 70.0
shovel_mat = "\u0001"
shovel_durability = 70.0
